version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:12.16.1
        working_directory: ~/be-the-hero-backend
        steps:
            - checkout

            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-

            - run: npm install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            - run: npm test
    deploy:
      docker:
        - image: circleci/node:12.16.1
      steps:
        - checkout
        - run:
            command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
